# Generated by Django 4.0.4 on 2022-05-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subcatgeory',
            new_name='username',
        ),
    ]
